### ISSUE TITLE
Add Vietnamese Support

### ISSUE THREAD

**Issue by amazingnerd** [RandomMaerks/Overused-Grotesk#10]
Hello,
I would be awesome when you support Vietnamese language. Love your typeface!

**Comment by RandomMaerks** [comment]
Hi! Are you using the latest version? Vietnamese characters have been added since the very first release of this typeface, so your version might be super old.

You can get the latest version [here](https://github.com/RandomMaerks/Overused-Grotesk/releases/tag/v0.4)!
