### ISSUE TITLE
Add Udmurt Support

### ISSUE THREAD

**Issue by codemurt** [RandomMaerks/Overused-Grotesk#12]
Hey, thank you for adding cyrillic characters. I really liked your font, is it possible for you to add support for the Udmurt language? You just need to add 5 additional cyrillic characters: `Ӧӧ Ӝӝ Ӟӟ Ӥӥ Ӵӵ`. Thank you in advance!

**Comment by RandomMaerks** [comment]
Sure! I'll add them in the next pre-release :)

**Comment by RandomMaerks** [comment]
Update: The glyphs have been added in commit 64c4e4c with rounded-dot variant ss03. They will be integrated into Italics and other widths
