### ISSUE TITLE
Permission to Add to Framer?

### ISSUE THREAD

**Issue by benjamindenboer** [RandomMaerks/Overused-Grotesk#14]
Hey! I am reaching out via an issue to see if it would be okay for us to add Overused Grotesk to Framer (http://framer.com/) — I am creating a manually curated selection of open source fonts to add to our font picker and would love to add this one.

Sorry for making a ticket for it :-)

Best,
Benjamin

**Comment by RandomMaerks** [comment]
Hi Benjamin! Yes, you can add the typeface to your font picker however you want.

Just one question though—does the builder automatically update fonts? Overused Grotesk is still a work in progress, and I'm afraid people would start making websites with an unfinished product.
