### ISSUE TITLE
Add other font formats and css usage

### ISSUE THREAD

**Issue by anurag-roy** [RandomMaerks/Overused-Grotesk#3]
Hey, thanks for creating this amazing free font!

Can we have more formats like `woff` and `woff2` in the release zip like [Inter](https://github.com/rsms/inter) provides? These two formats are very popular choices among web developers, so it would be easier if it just ships in the zip instead of converting all ttf by hand.

Also, would be nice if we could add a .css file with the usage code (especially for the variable version). If required, I am able to help you on this.

**Comment by RandomMaerks** [comment]
Hi! I'm glad you like the typeface :D

Right now, I don't have the appropriate tools for generating webfonts (even though conversion tools are available everywhere on the web, I just thought there are better Python scripts that can do conversions (for some reason)). Besides, the fonts aren't even finished yet. So generating webfonts isn't something I'm prioritising at this moment.

Also if you could help with webfont generation, .css code or anything web-related, I would highly appreciate your effort!

**Comment by RandomMaerks** [comment]
`woff` and `woff2` are now available for webfont usage.
From release `[v0.3.1](https://github.com/RandomMaerks/Overused-Grotesk/releases/tag/v0.3.1)`, both font file extensions will be included 👌

For now, I'll close the issue. If there are further problems with webfonts or the .css code, feel free to reopen it.
