### ISSUE TITLE
optional: add unicode support information?

### ISSUE THREAD

**Issue by berrymot** [RandomMaerks/Overused-Grotesk#6]
i see no specific table/list of what unicode blocks this covers. maybe add one? u don't have to though

**Comment by RandomMaerks** [comment]
Right now, I still want to add more glyphs, and updating the list every time I update would be a pain. But I'll still try to put a list like that somewhere in the [`documentation`](https://github.com/RandomMaerks/Overused-Grotesk/tree/main/documentation) folder.

FontForge has already done most of the job for me, so this is possible.

Thank you for reporting!

**Comment by berrymot** [comment]
:3

**Comment by RandomMaerks** [comment]
Hi again!

I added [`unicode-ranges.md`](https://github.com/RandomMaerks/Overused-Grotesk/blob/main/documentation/unicode/unicode-ranges.md) to the documentation folder.

If you have any questions, please let me know.

**Comment by berrymot** [comment]
(maybe do this for your other fonts too?)

**Comment by RandomMaerks** [comment]
Droide already has a unicode-ranges.md file 👍

Phlatt Grotesk... i mean.... it has 1.8k glyphs.......... maybe... not now..?

**Comment by berrymot** [comment]
skdjfhdjg

**Comment by RandomMaerks** [comment]
that's kinda true tbh

**Comment by RandomMaerks** [comment]
documentation for [phlatt grotesk](https://github.com/RandomMaerks/Phlatt-Grotesk/blob/main/documentation/unicode-ranges.md) is here
i can finally slep
no more manual labour !!!,,,,,,

**Comment by RandomMaerks** [comment]
documentation for this project has also just been updated to match with the source
further changes to the unicode table like the addition of cyrillic, small caps, etc. will also be included in the file

i'll close the issue for now. work here is DONE, and i am DONE WELLDONE MEDIUM RARE MEDIUM MEDIUM WELL LEGENDARY
